# Normalization Problem

In [3]:
import numpy as np

#creates a random 5x5 array (values between 0 and 1)
X = np.random.random((5, 5))

#finds the mean of all the elements in X
mean_X = X.mean()

#finds the standard deviation (how spread out the values are)
standard_dev_X = X.std()

#apply the normalization formula
#Z = (X - mean) / standard deviation
#makes the new data have a mean ~0 and std ~1
Z = (X - mean_X) / standard_dev_X

#save the normalized array
np.save("X_normalized.npy", Z)

#print results
print("Original X: \n", X) #shows the 5x5 array in random
print("\nMean:", mean_X) #shows the mean
print("Standard Deviation:", standard_dev_X) #shows the standard deviation
print("\nNormalized X (Z): \n", Z) #shows the normalized array 

Original X: 
 [[0.14661895 0.53823886 0.66192754 0.54618685 0.38421772]
 [0.77800956 0.27841796 0.76162777 0.62045288 0.66057582]
 [0.62699421 0.49027305 0.51773044 0.9104458  0.26031804]
 [0.6974951  0.10294013 0.77644447 0.96308654 0.66023285]
 [0.19715427 0.08574931 0.7002726  0.60966152 0.0302235 ]]

Mean: 0.5202118284128536
Standard Deviation: 0.2596009959119791

Normalized X (Z): 
 [[-1.4391042   0.06944129  0.54589819  0.10005747 -0.5238582 ]
 [ 0.9930537  -0.93140577  0.92994998  0.3861351   0.54069126]
 [ 0.4113327  -0.11532611 -0.00955847  1.50320677 -1.00112787]
 [ 0.68290675 -1.60735786  0.98702487  1.70598231  0.53937011]
 [-1.24443884 -1.67357801  0.69360585  0.34456604 -1.88746706]]


# Divisible by 3 Problem

In [5]:
import numpy as np

#creates an array of integers from 1 to 100
numbers = np.arange(1, 101)

#squares each integer in the array
squares = numbers**2

#reshapes the squared values into a 10x10 matrix
A = squares.reshape(10, 10)

#selects only the squared numbers that are multiples of 3
div_by_3 = squares[squares % 3 == 0]

#saves the divisible-by-3 results into a .npy file
np.save ("div_by_3.npy", div_by_3)

#displays the numbers divisible by 3
print(div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
